name: .NET

env:
  DOTNET_VERSION: 3.1.x
  AZURE_FUNCTIONAPP_PACKAGE_PATH: 'GitHubActionsAzureDeploy/GitHubActionsChallengeFunctionApp'
  AZURE_FUNCTIONAPP_NAME: "test-func-app0"
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
